apiVersion: v1
kind: Service
metadata:
  name: svc-tokenomics
  namespace: backend-mainnet
  labels:
    app: svc-tokenomics
spec:
  type: NodePort
  selector:
    app: svc-tokenomics
  ports:
  - name: http
    protocol: TCP
    port: 3003
    targetPort: 3003
    nodePort: 30003
