apiVersion: v1
kind: Service
metadata:
  name: svc-loanpool
  namespace: backend-mainnet
  labels:
    app: svc-loanpool
spec:
  type: NodePort
  selector:
    app: svc-loanpool
  ports:
  - name: http
    protocol: TCP
    port: 3005
    targetPort: 3005
    nodePort: 30005
