apiVersion: v1
kind: Service
metadata:
  name: svc-governance
  namespace: backend-mainnet
  labels:
    app: svc-governance
spec:
  type: NodePort
  selector:
    app: svc-governance
  ports:
  - name: http
    protocol: TCP
    port: 3006
    targetPort: 3006
    nodePort: 30006
