apiVersion: v1
kind: Service
metadata:
  name: svc-tax
  namespace: backend-mainnet
  labels:
    app: svc-tax
spec:
  type: NodePort
  selector:
    app: svc-tax
  ports:
  - name: http
    protocol: TCP
    port: 3007
    targetPort: 3007
    nodePort: 30007
