apiVersion: v1
kind: Service
metadata:
  name: svc-identity
  namespace: backend-mainnet
  labels:
    app: svc-identity
spec:
  type: NodePort
  selector:
    app: svc-identity
  ports:
  - name: http
    protocol: TCP
    port: 3001
    targetPort: 3001
    nodePort: 30001
