apiVersion: v1
kind: Service
metadata:
  name: svc-organization
  namespace: backend-mainnet
  labels:
    app: svc-organization
spec:
  type: NodePort
  selector:
    app: svc-organization
  ports:
  - name: http
    protocol: TCP
    port: 3004
    targetPort: 3004
    nodePort: 30004
