apiVersion: v1
kind: Service
metadata:
  name: svc-admin
  namespace: backend-mainnet
  labels:
    app: svc-admin
spec:
  type: NodePort
  selector:
    app: svc-admin
  ports:
  - name: http
    protocol: TCP
    port: 3002
    targetPort: 3002
    nodePort: 30002
